# Generated by Django 3.1.2 on 2020-11-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='endOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, null=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('call', models.FloatField(null=True)),
                ('stopLoss', models.FloatField(null=True)),
                ('Target1', models.FloatField(null=True)),
                ('Target2', models.FloatField(null=True)),
                ('Target3', models.FloatField(null=True)),
                ('Target4', models.FloatField(null=True)),
            ],
        ),
    ]
