# Generated by Django 3.1.2 on 2020-11-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofday',
            name='closePrice',
            field=models.FloatField(null=True),
        ),
    ]
