# Generated by Django 3.1.2 on 2020-11-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_endofday_closeprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endofday',
            name='id',
        ),
        migrations.AlterField(
            model_name='endofday',
            name='symbol',
            field=models.CharField(default='ERROR', max_length=30, primary_key=True, serialize=False),
        ),
    ]
