# Generated by Django 3.1.2 on 2020-12-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_endofday_currdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endofday',
            name='currDate',
        ),
    ]
