# Generated by Django 3.1.2 on 2020-12-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_endofday_currdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofday',
            name='currDate',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
