# Generated by Django 3.1.2 on 2020-12-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201212_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofday',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='endofday',
            name='low',
            field=models.FloatField(null=True),
        ),
    ]
