# Generated by Django 3.1.2 on 2021-01-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_endofday_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='endofday',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
